# fly.toml app configuration file generated for smartbrain-api25 on 2023-07-09T02:36:28+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "smartbrain-api25"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
